project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - href: recources.qmd
        text: Recources

format:
  html:
    theme: 
      - styles.scss
    mainfont: Pixelify Sans
    toc: true
    page-layout: full

editor: source

