project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: recources.qmd
        text: Recources

format:
  html:
    theme: 
      light: lumen
      dark: cyborg
    css: styles.css
    toc: false
    page-layout: full

editor: source

